namespace Pharos.Api.DTOs;

public record ResidentDto(
    int ResidentId,
    string CaseControlNo,
    string InternalCode,
    int SafehouseId,
    string? SafehouseName,
    string CaseStatus,
    string Sex,
    DateTime DateOfBirth,
    string CaseCategory,
    string? ReintegrationType,
    string? ReintegrationStatus,
    string? InitialRiskLevel,
    string? CurrentRiskLevel,
    string? AssignedSocialWorker,
    DateTime DateOfAdmission,
    string? PresentAge,
    string? LengthOfStay,
    DateTime? DateClosed
);

public record ResidentDetailDto(
    int ResidentId,
    string CaseControlNo,
    string InternalCode,
    int SafehouseId,
    string? SafehouseName,
    string CaseStatus,
    string Sex,
    DateTime DateOfBirth,
    string? BirthStatus,
    string? PlaceOfBirth,
    string? Religion,
    string CaseCategory,
    bool SubCatOrphaned,
    bool SubCatTrafficked,
    bool SubCatChildLabor,
    bool SubCatPhysicalAbuse,
    bool SubCatSexualAbuse,
    bool SubCatOsaec,
    bool SubCatCicl,
    bool SubCatAtRisk,
    bool SubCatStreetChild,
    bool SubCatChildWithHiv,
    bool IsPwd,
    string? PwdType,
    bool HasSpecialNeeds,
    string? SpecialNeedsDiagnosis,
    bool FamilyIs4ps,
    bool FamilySoloParent,
    bool FamilyIndigenous,
    bool FamilyParentPwd,
    bool FamilyInformalSettler,
    DateTime DateOfAdmission,
    string? AgeUponAdmission,
    string? PresentAge,
    string? LengthOfStay,
    string? ReferralSource,
    string? ReferringAgencyPerson,
    DateTime? DateColbRegistered,
    DateTime? DateColbObtained,
    string? AssignedSocialWorker,
    string? InitialCaseAssessment,
    DateTime? DateCaseStudyPrepared,
    string? ReintegrationType,
    string? ReintegrationStatus,
    string? InitialRiskLevel,
    string? CurrentRiskLevel,
    DateTime DateEnrolled,
    DateTime? DateClosed,
    DateTime CreatedAt,
    string? NotesRestricted
);

public record ResidentSummaryDto(
    int ResidentId,
    string CaseControlNo,
    string InternalCode,
    string CaseStatus,
    string? CurrentRiskLevel,
    string? ReintegrationStatus,
    decimal? LatestHealthScore,
    decimal? LatestEducationProgress,
    int TotalProcessRecordings,
    int TotalHomeVisitations,
    int OpenInterventionPlans,
    int TotalIncidents,
    string? LastEmotionalStateObserved,
    DateTime? LastSessionDate,
    DateTime? LastVisitDate
);

public record CreateResidentRequest(
    string CaseControlNo,
    string InternalCode,
    int SafehouseId,
    string CaseStatus,
    string Sex,
    DateTime DateOfBirth,
    string? BirthStatus,
    string? PlaceOfBirth,
    string? Religion,
    string CaseCategory,
    bool SubCatOrphaned,
    bool SubCatTrafficked,
    bool SubCatChildLabor,
    bool SubCatPhysicalAbuse,
    bool SubCatSexualAbuse,
    bool SubCatOsaec,
    bool SubCatCicl,
    bool SubCatAtRisk,
    bool SubCatStreetChild,
    bool SubCatChildWithHiv,
    bool IsPwd,
    string? PwdType,
    bool HasSpecialNeeds,
    string? SpecialNeedsDiagnosis,
    bool FamilyIs4ps,
    bool FamilySoloParent,
    bool FamilyIndigenous,
    bool FamilyParentPwd,
    bool FamilyInformalSettler,
    DateTime DateOfAdmission,
    string? ReferralSource,
    string? ReferringAgencyPerson,
    string? AssignedSocialWorker,
    string? InitialCaseAssessment,
    string? ReintegrationType,
    string? InitialRiskLevel,
    string? CurrentRiskLevel,
    DateTime DateEnrolled,
    string? NotesRestricted
);

public record UpdateResidentRequest(
    int? SafehouseId,
    string? CaseStatus,
    string? AssignedSocialWorker,
    string? ReintegrationType,
    string? ReintegrationStatus,
    string? CurrentRiskLevel,
    DateTime? DateClosed,
    string? NotesRestricted
);
